name: Node.js CI for Backend and Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js for Backend
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Backend Dependencies
      run: npm install
      working-directory: backend
    - name: Build Backend
      run: npm run build --if-present
      working-directory: Back-end
    - name: Test Backend
      run: npm test
      working-directory: Back-end

  frontend-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js for Frontend
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Frontend Dependencies
      run: npm install
      working-directory: Front-end
    - name: Build Frontend
      run: npm run build --if-present
      working-directory: Front-end
    - name: Test Frontend
      run: npm test
      working-directory: Front-end
