name: Node.js CI for Backend and Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js for Backend
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Backend Dependencies
      run: |
        if [ ! -f Back-end/package-lock.json ]; then
          npm install
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/${{ github.repository }}
          git add package-lock.json
          git commit -m "Add missing package-lock.json"
          git push
        else
          npm ci
        fi
      working-directory: Back-end
    - name: Build Backend
      run: npm run build --if-present
      working-directory: Back-end
    - name: Test Backend
      run: npm test
      working-directory: Back-end

  frontend-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js for Frontend
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Frontend Dependencies
      run: |
        if [ ! -f Front-end/package-lock.json ]; then
          npm install
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/${{ github.repository }}
          git add package-lock.json
          git commit -m "Add missing package-lock.json"
          git push
        else
          npm ci
        fi
      working-directory: Front-end
    - name: Build Frontend
      run: npm run build --if-present
      working-directory: Front-end
    - name: Test Frontend
      run: npm test
      working-directory: Front-end
